import sys
import zipfile
import glob
from pathlib import Path
from utils import get_version, get_jar_path
from utils import is_version_1_13_or_later


def extract_block_ids(minecraft_jar_path, minecraft_dir, version):
    """Extract block IDs from the Minecraft JAR file"""
    extracted_path = Path(minecraft_dir) / "versions" / version
    try:
        with zipfile.ZipFile(minecraft_jar_path, "r") as jar:
            jar.extractall(extracted_path)
            blockstates_dir = extracted_path / "assets/minecraft/blockstates"
            local_block_ids = []
            json_files = glob.glob(str(blockstates_dir / "*.json"))
            for file_path in json_files:
                block_id = Path(file_path).stem
                local_block_ids.append(block_id)
    except (FileNotFoundError, zipfile.BadZipFile) as e:
        print(f"\nError: {e}\n")
        print(f"Are you sure you have Minecraft {version}? Try another version.")
        sys.exit(1)
    return sorted(local_block_ids)


def save_to_file(block_ids, output_file, version, version_path):
    """Save block IDs to a Python file"""
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(f"# Block ID list of Minecraft {version}\n")
        f.write(f"#   auto-generated by get_block_id.py as block_{version_path}.py\n\n")
        for block_id in block_ids:
            formatted_id = f'{block_id.upper()} = "{block_id}"'
            f.write(formatted_id + "\n")


def main():
    """Main function to extract and save block IDs"""
    version = get_version()
    version_path = version.replace(".", "_")
    minecraft_jar_path = get_jar_path(version)

    if is_version_1_13_or_later(version):
        block_id_list = extract_block_ids(
            minecraft_jar_path, Path(minecraft_jar_path).parent, version
        )
        script_dir = Path(__file__).resolve().parent
        file_name = f"block_{version_path}.py"
        output_file = script_dir / file_name
        save_to_file(block_id_list, output_file, version, version_path)
        print(f"Block IDs have been written to:\n{output_file}")
    else:
        print("This version is not supported.")
        sys.exit(1)


if __name__ == "__main__":
    main()
